function Nodes = CreateNode(NodeNum)

VarName = {'time','Index','ParentIndex','Type','Level','Cost', ...
   'Dir','Step','ConfigRow','ConfigCol','ParentRow','ParentCol',...
   'Visits','Cost2Target','ConfigStr','ParentStr','ConfigMat',...
   'ParentMat','IsomorphismMatrices1','IsomorphismMatrices2','IsomorphismMatrices3'...
   'IsomorphismStr1','IsomorphismStr2','IsomorphismStr3','IsoSiz1r','IsoSiz1c','IsoSiz2r','IsoSiz2c','IsoSiz3r','IsoSiz3c','Manuver','Manuver_num'};
VarType = {'string','double','double','double','double',...
   'double','double','double','double','double','double','double'...
   ,'double','double','string','string','cell','cell','cell','cell'...
   ,'cell','string','string','string','double','double','double','double','double','double','string','double'};

Nodes = table('Size',[NodeNum,numel(VarName)],'VariableTypes',VarType,'VariableNames',VarName);

end
